### ISSUE TITLE
[Feature] Import option for bookmarks 

### ISSUE THREAD

**Issue by tushhr** [unimarkapp/unimark.app#1]
An option to import bookmarks from the browser.

**Comment by tushhr** [comment]
Hey @romanslonov, are you planning to add this feature on Unimark? If yes, can I work on this?

**Comment by romanslonov** [comment]
Hello, 

Yes it's planned. You can do it, sure.

**Comment by tushhr** [comment]
Thanks.
Just a few questions:
1. Where should this feature be added? Where should we add the button to Import?
2. What about the collection while adding bulk bookmarks? - Keep it as default "Websites"?
3. How this feature be implemented - as in the ux?

**Comment by romanslonov** [comment]
1. We can add import button next to the "add bookmark" button just with icon as I think it will be rarely used (in most cases at the beginning).
2. I think it's possible to group bookmarks from browser export to collections (by folder or title in html) and create them on import. Also we can add an option for user to just select a default collection where we should add the bookmarks.
3. I think in modal?

**Comment by tushhr** [comment]
@romanslonov, I have created PR for this - #2 , can you review?

**Comment by romanslonov** [comment]
Implemented in PR #2 

Thanks to @tushhr
