### ISSUE TITLE
Move bookmarks to another collection in bulk

### ISSUE THREAD

**Issue by vivekmiyani** [unimarkapp/unimark.app#3]
Title says it all!

---

Thanks for this awesome project 🥹!

**Comment by romanslonov** [comment]
Hello!

I am actually thinking about to remove collections completely, after using the app for a month I found them useless. For example if your bookmark belongs to a few collections. So what I think we really need is only tags, you can easily filter by them and found what you need. Example, you bookmarked an article about tech stuff, you can tag with `development` and with specific language or topic `django` so you can easily find all articles belongs to just `development` or `django` specific. Also need to redesign tags selector and make input search more useful. 

What you think? Curious to hear your feedback.

**Comment by vivekmiyani** [comment]
Okay, I haven't used app much. and I think you're right we just need tags. Maybe we can remove collections and show all tags on left sidebar for easy access?
